version: '3.8'
services:
  app:
    image: myapp:latest
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run start:dev
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - some-net
    depends_on:
      - db
  db:
    networks:
      - some-net
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: juninho22
      MYSQL_DATABASE: nest
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  some-net:
    name: custom_network
